<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Form extends CI_Controller
{
    

  public function add(){


        $this->form_validation->set_rules('strength','Strength','required');
        $this->form_validation->set_rules('personality','Personality','required');
        $this->form_validation->set_rules('passion','Passion','required');
        $this->form_validation->set_rules('finance','Finance','required');
        if ($this->form_validation->run()==false) {
            $this->load->view('form/index');
        } else{

                $data = array(
                'strength_id'=>$this->input->post('strength'),
                'personality'=>$this->input->post('personality'),
                'passion'=>$this->input->post('passion'),
                'finance'=>$this->input->post('finance'),
            );
               $id = $this->input->post('user_id');
               $user = $this->Users_model->get_by_id($id);
               if(empty($user->strength_id)){
                $this->Users_model->update($id,$data);
                $this->session->set_flashdata('complete','Thank you for completing the form');
                redirect('result');
            }else{

                redirect('result');
            }

        }
  }


    
}

/* End of file Form.php */
/* Location: ./application/controllers/Form.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-13 10:24:26 */
/* http://harviacode.com */