<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users extends CI_Controller
{
    
    public function login(){
        
        $this->form_validation->set_rules('username','Username','trim|required|min_length[4]');
        $this->form_validation->set_rules('password','Password','trim|required|min_length[4]|max_length[50]');
        $username = $this->input->post('username');
        $password = $this->input->post('password');
        if($this->form_validation->run()==false){
            $this->load->view('users/login'); 
        }else{

        $user = $this->Users_model->login_user($username,$password);

        //Vallidating users data
        if($user){

            /*$data = array(
                'user_id' => $user['id'],
                'username' => $username,
                'logged_in' => true,
                'strength' => $user['strength_id'], 
                );*/
            // Set session user_data

            $this->session->set_userdata('user_id',$user['id']);
            $this->session->set_userdata('username',$user['username']);
            $this->session->set_userdata('strength',$user['strength_id']);

             
      
            if ( $this->session->userdata('strength')=='1' ||  $this->session->userdata('strength')=='2'){
                 redirect('profile');        
            }else{

                 redirect('form/add');

            }

            #$this->session->set_flashdata('login','You are currently logged in');
                     
        }   else{
        // Set login error
            $this->session->set_flashdata('fail','Invalid user name or password');
            redirect('users/login');
        }

    }
}

    public function logout(){

        $this->session->unset_userdata('logged_in');
        $this->session->unset_userdata('user_id');
        $this->session->unset_userdata('Username');
        #$this->session->unset_userdata('strength');
        $this->session->sess_destroy();
        redirect('users/login');

        }


    public function register(){
        $this->form_validation->set_rules('username','Username','required');
        $this->form_validation->set_rules('password','Password','trim|required');
        $this->form_validation->set_rules('confirm','Password','trim|required|matches[password]');


        if ($this->form_validation->run()==false) {
                $this->load->view('users/register');            
        } else{

            $data = array(

                'username'=>$this->input->post('username'),
                'password'=>$this->input->post('confirm'),

            );

                $this->Users_model->insert($data); 
                $this->session->set_flashdata('registered','Login to complete your registration');
                redirect('users/login');
            
        }
    }


         
    
    
}

/* End of file Users.php */
/* Location: ./application/controllers/Users.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-14 14:03:25 */
/* http://harviacode.com */