<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_model extends CI_Model
{

    public $table = 'admin';
    public $table_two ='courses';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('password', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('password', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // Courses queries


    // insert into courses

    function insert_courses($data)
    {
        $this->db->insert($this->table_two, $data);
    }

        // Update courses    
    function update_courses($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table_two, $data);
    }

    function delete_courses($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table_two);
    }




    // get all courses

    function get_all_courses()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table_two)->result();
    }

    // get all courses by id

    function get_courses_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table_two)->result();
    }
    

    // Admin login

     public function login($username,$password){

        $this->db->where('username',$username);
        $this->db->where('password',$password);
        $result = $this->db->get('users');
        if($result->num_rows()==1){
            return $result->row(0)->id;
        } else{
            return false;
        }
    }


}

/* End of file Admin_model.php */
/* Location: ./application/models/Admin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-02 11:51:23 */
/* http://harviacode.com */